### ISSUE TITLE
Document the project

### ISSUE THREAD

**Issue by BurningEnlightenment** [deeplex/deeplog#1]
Document the code and its anticipated usage patterns making this library fit for the general use.

Add reference documentation with sphinx, some inline documentation and a bit of examples code. Document the file formats in use and their design background. Write down the anticipated release strategy. Finally write a README worth its disc space.

## Tasks
- [ ] Write a README.md
- [ ] Document the release flow
- [x] #11
- [ ] #21 
- [ ] Investigate whether integrating sphinx with doxygen makes sense
- [ ] Document the `.dlog` file format (log regord container)
- [ ] Document the `.drot` file format (log rotation/aggreggation)
- [ ] Document the `.dlrb` file format (ringbus)
- [ ] Write a general component overview
- [ ] Document the error handling approach
- [ ] Document the relevance of attributes and their API
- [ ] Document the log source API
- [ ] Document the log sink API
- [ ] Document the log record container API
