### ISSUE TITLE
Improve the test coverage

### ISSUE THREAD

**Issue by BurningEnlightenment** [deeplex/deeplog#2]
Extend the test suite to the point where code changes can be committed with general confidence in their soundness.

## Tasks
- [ ] Write integration tests covering the common usage scenarios.
- [ ] Write comprehensive tests for the log macros.
- [ ] Write tests for the log clock time conversion functions.
- [ ] Write comprehensive tests for the file database implementation.
- [ ] Write tests for the attribute transmorpher.
- [ ] Write tests for the argument transmorpher.
- [ ] Write comprehensive tests for the log source API
- [ ] Write comprehensive tests for the log sink API and its implementations
- [ ] Write tests for the file_stream classes.
- [ ] Write tests for the interleaving stream classes.
- [x] #15
