### ISSUE TITLE
Add a log record filter to the TUI

### ISSUE THREAD

**Issue by BurningEnlightenment** [deeplex/deeplog#4]
Create a filter language which allows the user to precisely filter log records by record message, severity, timestamp or any recognized attribute. Integrate said filter language into the TUI, i.e. provide the user with an input field for his filter and do the actual filtering.

## Tasks
- [ ] Write the filter language specification
- [ ] #13
- [ ] Create a parser for the filtering language with Boost.Spirit
- [ ] Derive an evaluator which verifies that a log record matches the filter
- [ ] Instantiate and invoke the parser/evaluator from the TUI
- [ ] \(Optional) Add a AST view for the filter to the TUI
